### ISSUE TITLE
Small regression: cursor is not hidden on select

### ISSUE THREAD

**Issue by SamSchott** [Exahilosys/survey#1]
Thanks again for putting this up! And for a really great library.

I noticed a small regression compared to the first version: The cursor is no longer hidden for `Select` or `MultiSelect` prompts. There probably is a `_cursor.hide()` missing in somewhere in `.tools.Select.get()`.

**Comment by Exahilosys** [comment]
Hey, good observation! There's quite a few places where the cursor should be hidden, with the select tool being one of them. I will be releasing a version update addressing this issue super soon.
