### ISSUE TITLE
Callback sometimes not invoked on delete event

### ISSUE THREAD

**Issue by SamSchott** [Exahilosys/survey#11]
Replicating the advanced example from the docs https://survey.readthedocs.io/quickstart.html#advanced, I noticed that the callback does not get invoked on deletions when `multi = False`. It still gets invoked on insertions. If `multi = True`, everything works as expected.

**Comment by Exahilosys** [comment]
Excellent catch! The event handler for `delete` was being overwritten on `LineEditor`. Should work fine now.
