### ISSUE TITLE
Python requirement is >= 3.7, contrary to marker in setup.py

### ISSUE THREAD

**Issue by SamSchott** [Exahilosys/survey#13]
The `survey.theme` module makes use of `namedtuple`s with defaults. The `defaults` parameter has only been introduced in Python ~3.8~ 3.7 which results in an error when importing that module.

**Comment by Exahilosys** [comment]
Great catch! I'm unable to work on it right now but I'd rather find an alternative to defaults rather than up version requirements.

**Comment by SamSchott** [comment]
Small typo in my initial comment: defaults where introduced in Py 3.7.

The simplest alternative would be to switch from namedtuple to classes that just serve to hold a number of attributes. This would essentially be a more verbose option to either namedtuple or the dataclasses introduced in Python 3.7.

**Comment by SamSchott** [comment]
Nice!
