### ISSUE TITLE
Select keeps expanding the number of rows

### ISSUE THREAD

**Issue by SamSchott** [Exahilosys/survey#2]
Another small regression:

When stepping through the list of options and hitting the bottom or the top, the number of options keeps increasing with new lines printed for existing options. This is probably just a small oversight somewhere in tracking the cursor position.

On a side note: the keyboard shortcuts for selecting items are a bit confusing without reading the documentation. Maybe a default hint would be good?

**Comment by Exahilosys** [comment]
Hey, I do not seem to be able to replicate the described behaviour, maybe provide a code snippet reproducing it?
As for the side note, some hints would be cool indeed! Can't expect every end user reading the documentation 😉

**Comment by SamSchott** [comment]
The issue seems to happen when the number of options > `limit`. What is the expected behaviour in this case? Scrolling or extending the list?

In either case, the list extended with the already displayed options instead of the new ones. And keeps extending the further you go...

**Comment by SamSchott** [comment]
Sorry, that wasn't quite correct: The list is extended with the new choices first. Then it keeps expanding further.

**Comment by Exahilosys** [comment]
Ah yes, I see what's wrong with it, working on a fix, good catch!

**Comment by SamSchott** [comment]
Wow, quick work :) Also, while we are at wish lists -- some kind of "has more" indicator would be nice if not all options are displayed.

**Comment by Exahilosys** [comment]
I'm at a loss on how to implement this without over-cluttering with additional lines over or bellow the tool. Something like this would also need to be implementable with the multiline editor tool, as it also offers the same scrolling effect.

I think that context could suffice in this case, as simply pressing "up" brings the user to the end of the list, immediately indicating whether there are more option. If conveying the amount of rows is a must, a hint could also help out.

**Comment by SamSchott** [comment]
Fair point. I do like the very clean interface.
