### ISSUE TITLE
Is there any way to set a default value for numerics?

### ISSUE THREAD

**Issue by RobLOlson** [Exahilosys/survey#23]
I'm not seeing this in the documentation, but is it possible to set a default value for numeric?  For example:

```python
count = survey.routines.numeric("Enter an integer: ", decimal=False, default=5)
```

Currently this produces a keyword error, i.e., it's not expecting a 'default' argument.  Is there some other way?

**Comment by Exahilosys** [comment]
You can use `value = 5` to have an initial value. Here is the [numeric widget documentation](https://survey.readthedocs.io/reference.html#survey.widgets.Numeric.params.value) which is used under the hood. 

Please close this ticket if this answers your question 😊

**Comment by RobLOlson** [comment]
Ah, that's what I was looking for, thanks!
