### ISSUE TITLE
Capturing ctrl+n/ctrl+p event

### ISSUE THREAD

**Issue by PJGaetan** [Exahilosys/survey#30]
Hi, 

I'm trying to use the `select` widget and to navigate between the choices using the ctrl+p and ctrl+n keys.

I tried using a `callback` function to add this custom behaviour but I'm not getting event for those specific keys.

Is there another way to achieve such an effect ?

**Comment by Exahilosys** [comment]
I'm afraid this is not possible with the current implementation of how keypresses are being captures and interpreted.

**Comment by PJGaetan** [comment]
Would you be open to add those event (`\016`, `\020`),  in the `EventType.control` mapping, or would there be unwanted effect in doing so ?

https://github.com/Exahilosys/survey/blob/1fe21970b8a7a3634e2a062c732c9a379e3ca073/survey/_core/_source.py#L88-L101

**Comment by Exahilosys** [comment]
It would definitely be a solution, but hardcoded events is something I'd like to keep to its bare minimum. How come you require ctrl+p and ctrl+n? They seem a bit odd for navigational purposes.

**Comment by PJGaetan** [comment]
I am used to those I would say, ctrl+p / ctrl+n are emacs key biding, and j / k are vi like key biding. I got used to them in popular software (you can go up and down in VSCode command pallet using ctrl+p and ctrl+n for example).

In Go, popular packages uses ctrl+p / ctrl+n and j / k (only when not focused to filter) : 
- [survey](https://github.com/AlecAivazis/survey)
- [charmbracelet ecosystem](https://github.com/charmbracelet/huh).

In python : 
-  [questionary](https://github.com/tmbo/questionary) 
- Not tried personally this one yet but the docs advertise for it [python-prompt-toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit?tab=readme-ov-file#prompt_toolkit-features)

**Comment by Exahilosys** [comment]
Fair, I'm convinced! Sorry for the silly question but for me, VS goes down with ctrl+p, whilst ctrl+n just opens a new document. Which one is supposed to go up and which one down?

**Comment by PJGaetan** [comment]
- `ctrl` + `p` : goes up
- `ctrl` + `n` : goes down

I don't know if I have personal settings overriding this, but when I'm here (figure below) and I press ctrl+p and ctrl+n, I'm able to navigate up and down this menu in vscode.
<img width="608" alt="image" src="https://github.com/Exahilosys/survey/assets/43468407/d4ec1835-bd88-4848-b425-ee29190b8a78">
