### ISSUE TITLE
Survey doesn't work in PyCharm's Run/Debug Console Output

### ISSUE THREAD

**Issue by Neltherion** [Exahilosys/survey#33]
Survey doesn't work in Pycharm and running this simple exam doesn't show anything and the program gets stuck (on Windows):

```
import survey

colors = ('red', 'green', 'blue', 'pink', 'silver', 'magenta')
index = survey.routines.select('Pick a color: ', options=colors)
print(f'Answered {index}.')
```

**Comment by Neltherion** [comment]
It seems to be related to [this](https://stackoverflow.com/questions/63543251/no-windows-console-found-are-you-running-cmd-exe) problem.

**Comment by Exahilosys** [comment]
This seems to be an issue related with pycharm and not the library. As long as there is an stdout that feeds into a console supporting ansi sequences, there should be no issue.
