### ISSUE TITLE
How to set `survey.routines.datetime` to use ISO format?

### ISSUE THREAD

**Issue by Patrick-Ze** [Exahilosys/survey#34]
I'm using the `survey.routines.datetime` feature to collect datetime responses, I need to customize the time format to use ISO format timestamp (e.g. `YYYY-MM-DD HH:mm:ss`).

Could you please provide guidance on how to configure `survey.routines.datetime` to use the ISO format timestamp? I've checked [the documentation](https://survey.readthedocs.io/reference.html#survey.routines.datetime), but couldn't find any information on this specific topic.

Thanks in advance for your help!

**Comment by Exahilosys** [comment]
Heya! This should do the trick:
```py
survey.routines.datetime(date_delimit = '-', time_delimit = ':', attrs = ('year', 'month', 'day', 'hour', 'minute', 'second'))
```
As mentioned in the [routine doc](https://survey.readthedocs.io/reference.html#survey.routines.datetime) it uses the [DateTime widget](https://survey.readthedocs.io/reference.html#survey.widgets.DateTime) which details all acceptable parameters.

Feel free to close this if it answers your question 🙂

**Comment by Patrick-Ze** [comment]
That indeed works, thank you so much for your support!
