### ISSUE TITLE
Description of select options

### ISSUE THREAD

**Issue by nexgen** [Exahilosys/survey#35]
Is there anyway I can display description of select options?

For example:

Choose Breakfast:
* Omlete
* Pizza

If the selection is at Omlete it should show description as "Nutritious and Healthy", for Pizza it would be: "Tasty but Unhealthy"

**Comment by Exahilosys** [comment]
You could use the fact that `hint` can be a callable that takes the widget as its first argument, then, resolve the widget in its index and use that to return a description (ideally, also include the built-in hint like I did below).

```py
import survey

options = ('Omlete', 'Pizza')

descriptions = {
    'Omlete': 'Nutritious and Healthy',
    'Pizza': 'Tasty but Unhealthy'
}

def hint(widget, *args):
    index = widget.resolve()
    option = options[index]
    description = descriptions[option]
    hint = survey.routines._select_hint(widget, *args)
    return f'{hint} {description}'

index = survey.routines.select(options = options, hint = hint)
```
![see](https://github.com/user-attachments/assets/bbf9be16-e8b7-4500-86b9-4d45374c23b2)

Feel free to close the issue if this answers your question 🙂

**Comment by nexgen** [comment]
Excellent! Thank you very much.
