### ISSUE TITLE
Mismatch between label text and option order when using `label`

### ISSUE THREAD

**Issue by Patrick-Ze** [Exahilosys/survey#36]
I'm experiencing an issue where the label text and option order don't seem to match when using labels in my application. Specifically, the label text appears to be in a different order than the corresponding options.

```python
import survey

colors = ('red', 'green', 'blue', 'pink', 'silver', 'magenta')
LABEL_MAP = {
    'red': 'Red Color',
    'green': 'Green Color',
    'blue': 'Blue Color',
    'pink': 'Pink Color',
    'silver': 'Silver Color',
    'magenta': 'Magenta Color'
}

def label(index, tile):
    return LABEL_MAP.get(colors[index])

index = survey.routines.select('Pick a color: ', options=colors, label=label)
```
When I run the script, the output is
```
? Pick a color:  [filter: type | move: ↑↓]
> red    Red Color
  green  Magenta Color
  blue   Silver Color
  pink   Pink Color
  silver Blue Color
  magentaGreen Color
```
The first line `red    Red Color` is ok but other lines are wrong.

Could you please help me understand why this might be happening and if there's a way to resolve this issue? I'd greatly appreciate any guidance or clarification on this matter.

Thank you for your time and assistance!

**Comment by Patrick-Ze** [comment]
@Exahilosys Thank you for your quick response ❤️ 

I'm not entirely clear on the workings of the survey, but I did have some doubts during debugging. Is the line `index *= -1` supposed to be at the beginning? I mean
```python
            def funnel_enter_entry_get(index):
                if not axis:
                    index *= - 1
                spot = _get_mesh_spot(axis, index)
                tile = self._mutate.tiles.get(spot)
                value = label(index, tile)
```

Because the value of `self._mutate.tiles` is as follows: 
![image](https://github.com/user-attachments/assets/84b0e5d9-24dd-45d6-be4f-c9a50f6a06cc)
except for the first time when `spot=(0,0)`, all subsequent times will result in an inability to get a tile due to `spot` being a negative number (e.g. `(-1,0)`), thus the tile passed to the `label` function is `None`.

**Comment by Exahilosys** [comment]
You are absolutely right, I tested with your example and forgot to actually check the provided value.
