### ISSUE TITLE
Python version compatibility

### ISSUE THREAD

**Issue by SamSchott** [Exahilosys/survey#4]
Survey uses some Python 3.8+ syntax. As far as I can see, this applies only to the `cursor` module with the positional-only arguments.

Is there any particular advantage to this? If not, it would be nice to drop those and have better backward compatibility. But I don't know what `wrapio` requires. Especially the `asyncio` API has seen some changes in recent versions.

**Comment by SamSchott** [comment]
Also, regarding the very active contributions, I'm planning to use survey for a CLI in my own project https://github.com/SamSchott/maestral. It currently supports Python 3.6+.

I have looked at many alternatives before but they were either very large dependencies, based on `prompt_toolkit`, or inconsistent in code design and visual appearance.

**Comment by Exahilosys** [comment]
Writing the `io.py` and `cursor.py` modules began with the intent to have them in a separate, standalone module; hence the seemingly nonsensical parameter restrictions. Removed them!

I also changed up some asyncio stuff on `wrapio` and made sure there are no f-strings anywhere in the code. I can't think of a reason why 3.5 wouldn't suffice as the base version for both libraries. I cannot test that atm, but I'd be glad to re-open this if any jabs are found.

Also, I can't wait to see what you do with this library, it's always an honor seeing it used in ambitious projects! If you feel like there's any tools or features that could be added along the way, feel free to suggest 😃!

**Comment by SamSchott** [comment]
Thanks a lot! I'll keep you updated when the new CLI might be released.

**Comment by SamSchott** [comment]
Have a look at this beautiful dialog flow. Especially the selection of folders is a massive improvement over the previous UI:

![command-line](https://user-images.githubusercontent.com/20974290/100517535-0936df80-3183-11eb-81eb-6019c7a6273f.gif)

**Comment by Exahilosys** [comment]
This is so pretty! Love the subtle customisation here and there! The tick looks quite pretty for multiselect, might change it to be the default. Also, I have a feeling you're really gonna like the new couple functions I added 🙂!

![Showcase](https://user-images.githubusercontent.com/22274370/100520094-b837e300-31a4-11eb-95e5-bb74d05b832f.gif)

**Comment by SamSchott** [comment]
About the ticks: I would probably stick with `x` as a safer ASCII character. Also, they look pretty on macOS but Ubuntu uses a more playful font for ticks which offsets them to the right:

<img width="309" alt="Screenshot 2020-11-28 at 16 51 34" src="https://user-images.githubusercontent.com/20974290/100521256-45296f00-319a-11eb-8f9c-6ba7eb87bb5c.png">

Not as clean anymore.

**Comment by SamSchott** [comment]
The path selection is really neat. I can see that being very useful. The key bindings may potentially be problematic: users have been trained for years to use tab completion in the console. Since the input format here is different (it's not a completion system but rather a tree traversal), it should be fine. But my first instinct was to use tab completion, I only checked the hint after this didn't work...

**Comment by SamSchott** [comment]
Never mid, thinking about it, the arrow keys are absolutely the right choice. They allow you to go back as well. And it really is not a completion system!

**Comment by SamSchott** [comment]
And it's released: https://github.com/SamSchott/maestral/releases/tag/v1.3.0. I think using survey is more than just a fancy gimmick -- especially `selection` enables exposing settings and functionality in the CLI that would otherwise be difficult to provide.

**Comment by Exahilosys** [comment]
Congrats 🎊

I just updated a bunch of stuff that couldn't be done little-by-little so make super duper sure there's no compatibility issues!
