### ISSUE TITLE
Consider issuing releases

### ISSUE THREAD

**Issue by coxackie** [Exahilosys/survey#5]
Hi there. This is not a bug, but I wanted to ask (in preparation for adding this package in the Arch User Repository, as I can now see that `maestral` is suing it), whether you would consider issuing releases in this repo as well, as is the usual case. This would be very helpful.

**Comment by Exahilosys** [comment]
Hello and thanks for showing interest! 
I plan on setting up a continuous integration workflow soon, and releases will be part of it!

**Comment by coxackie** [comment]
excellent - thanks for the prompt response. Please keep this open and close it what the first release happens, so I get notified.

**Comment by Exahilosys** [comment]
First release is up!

**Comment by coxackie** [comment]
Many thanks, and sorry for being a bit of a pain here, but...
`PyPi and Github release version numbers will likely not align [...]`

 Is this really a good idea? Other projects will ask for dependencies with semantic version of... which? If these are not aligned, how are the package versions from distros are connected with the ones from PyPi? I am positive this will create a mess. I understand you may not be very happy with the PyPi release versions, but please consider aligning them, to make maintainer's life easy.

**Comment by Exahilosys** [comment]
Not being a pain at all! I'm fully open to discussing this, but I still fail to see the issue here. 

Installation should be done via `pip`, fetching distros from PyPi directly, from Github using the `git+` option, or via directly installing the `.tar.gz` assets. On any scenario, the dependencies for the specific version being installed will be handled by pip.

Is there any argument circumventing this one?

**Comment by coxackie** [comment]
Well, In Arch Linux most, the way that python packages are, well, packaged, is outside pip. See for example the list [here](https://www.archlinux.org/packages/?sort=&arch=any&q=python-&maintainer=&flagged=) (that goes on for 26 pages). To build the package, done from github usually, one would use the version numbering in the repo. Pacman (the package manager) is very picky about dependencies, so if there is discrepancy things will ball apart.

 Arch is not so much of a niche distro, quite a number of others are based on it. This is why I think version numbers should be aligned.

**Comment by Exahilosys** [comment]
I'm not familiar with Arch or Pacman, so excuse me if I misunderstand anything. Since, from what I understand, Github is the repository used for installing packages, and `PyPi` is never fiddled with, what's the issue if the version numbers between the two don't align? Release assets should always come packaged with metadata describing which dependencies they need.

**Comment by coxackie** [comment]
ok, I will give as an example `maestral` that I am maintaining. Go [here](https://aur.archlinux.org/packages/maestral/). you see several dependencies (which `python-survey` will have to be in the future). The PKGBUILD files in all these dependencies specifies the version, which is pulled from github (mostly). This is the metadata used for checking dependency validity. Now, maestral will be requiring certain version for `python-survey` in its setup file, which will be the PyPi one. If versions are not aligned, the maintainer (me, or whoever else) would have to convert this to whatever the github equivalent version is, something that is surely destined to fail in the future.

 Of course, if you have an alternative way of doing this (again, which gets dependencies aligned with PyPi and does not require manual intervention), I will be more than happy to follow it.

**Comment by Foxboron** [comment]
@coxackie adding version bounds for this is nonesense. Even if the upstream tag is wrong, there is no reason for the hardcoding of the versions as you are doing.

**Comment by Exahilosys** [comment]
Regardless, I understand that mismatching versions begs for confusion like this, changed the first release to the respectful PyPi version, and will continue to do so!

**Comment by coxackie** [comment]
Many thanks @Exahilosys . Regarding `setup.py`: there is no `Readme.rst`, but there is `Readme.md`. I also see that this `survey` requires `wrapio`, which I would also have to package, I guess. Maybe I can just provide a git version of that...

**Comment by Exahilosys** [comment]
Good catch! I will also go through and start releasing all of my git projects, wrapio will be one of them, of course 🙂

**Comment by coxackie** [comment]
Thanks, releasing also `wrapio` will be indeed convenient.
