### ISSUE TITLE
Semantic versioning?

### ISSUE THREAD

**Issue by SamSchott** [Exahilosys/survey#9]
Anticipating breaking changes, I have pinned the maestral requirement to survey < 3.0 to prevent any issues. Though I probably should have checked with you first, because I noticed too late that there are already breaking changes in 2.2.0.

Are you planning to use semantic versioning? If not, this is fine as well. I will just have to be a lot more cautious in specifying my dependencies...

**Comment by Exahilosys** [comment]
I'll be honest and say that not bumping to 3.0.0 was a mistake on my end since there were indeed breaking changes introduced. I plan on moving forward with properly following semantic versioning from now on. A thousand apologies for any inconvenience!

**Comment by Exahilosys** [comment]
Closed a bit early, but versions should be properly set now.

**Comment by SamSchott** [comment]
Thanks for the prompt response! And yeah, I released v1.3.0 a bit too early. My hand was forced by another breaking change to the Python Dropbox SDK which came with a minor release. Though they ended up yanking that release from PyPI as well after I complained...

The lesson learned for me really is to be conservative regarding dependency versions.
